version: "3.9"

services:
  postgres-services:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: restaurant_db
    ports:
      - "26013:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - restaurant_network
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    restart: unless-stopped

    ports:
      - "26011:9000"   # API
      - "26012:9001"   # Console (if supported)

    environment:
      RUSTFS_ROOT_USER: admin
      RUSTFS_ROOT_PASSWORD: admin123456

    volumes:
      - rustfs_data:/data

    networks:
      - restaurant_network
  
  nginx:
    image: nginx:1.27-alpine
    container_name: restaurant_nginx
    restart: unless-stopped
    depends_on:
      - restaurant_backend_service
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - restaurant_network

  restaurant_backend_service:
    container_name: restaurant_backend_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "26010:8081"
    depends_on:
      - postgres-services
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-services:5432/restaurant_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin@123
    networks:
      - restaurant_network
    restart: always  

networks:
  restaurant_network:
    driver: bridge

  
volumes:
  postgres_data:
  rustfs_data:

  
