spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: sarana-resturant-system
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-services:5432/restaurant_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin@123}
    driver-class-name: org.postgresql.Driver
  Jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Phnom_Penh
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2KB

server:
  tomcat:
    max-http-form-post-size: 104857600
    max-swallow-size: 104857600
  port: 8081

springdoc:
  api-docs:
    enabled: true

Cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:dhnnf6f19}
  api_key: ${CLOUDINARY_API_KEY:285234396881491}
  api_secret: ${CLOUDINARY_API_SECRET:c7rYc264pUv8wEcfyv0YcI5zJ5k}

rustfs:
  endpoint: ${RUSTFS_ENDPOINT:http://rustfs:9000}
  access-key: ${RUSTFS_ACCESS_KEY:admin}
  secret-key: ${RUSTFS_SECRET_KEY:admin123456}
  bucket: ${RUSTFS_BUCKET:restaurant-management-system}

app:
  jwt:
    secret: ${APP_JWT_SECRET:MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg=}
    access-expiration-seconds: 90000
    refresh-expiration-seconds: 864000
